## Q-Learning with Tables in OpenAI FrozenLake gym environment

Import Libraries

In [1]:
import gym
import numpy as np

Load OpenAI Frozen Lake Gym environment 

In [2]:
env = gym.make('FrozenLake-v0')

[2018-01-25 00:15:37,817] Making new env: FrozenLake-v0


In [6]:
print(env.observation_space.n, env.action_space.n)

16 4


Implementing Q-Learning algorithm with Tables

In [3]:
#Initialize table with all zeros to be uniform
Q = np.zeros([env.observation_space.n, env.action_space.n])
#Learning parameters
lr = .8
y = .95
num_episodes = 2000
#creating lists to contain total rewards and steps per episode
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #Q-Learning Table algorithm
    while j<99:
        j+=1
        #Choose an action by greedily(with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [4]:
print("Average rewards over Episodes : " + str(sum(rList)/num_episodes))

Average rewards over Episodes : 0.47


In [5]:
print("Q-Table Values : \n")
print(Q)

Q-Table Values : 

[[  8.47040098e-03   7.66712030e-03   8.16426174e-02   8.25636136e-03]
 [  1.48353126e-03   7.42615090e-04   9.90834013e-04   5.94361785e-02]
 [  1.37220141e-03   1.52496188e-02   9.06307786e-04   3.66456959e-03]
 [  1.72175590e-04   8.16672458e-04   2.97340528e-04   4.00278237e-02]
 [  1.13422189e-01   2.17373255e-04   1.92560258e-03   1.06520001e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.24833059e-04   8.87623332e-05   1.55509432e-03   4.78402985e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.77451522e-03   0.00000000e+00   7.34414964e-04   1.69459478e-01]
 [  7.82494995e-04   9.19990620e-02   2.84817940e-03   5.44614652e-04]
 [  3.88074640e-01   1.80590050e-04   2.56858091e-04   1.26232917e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.87450726e-03   3.27974447e-01   3.7